# Generated by Django 4.1.13 on 2025-05-28 19:03

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("activity_type", models.CharField(max_length=50)),
                ("duration", models.IntegerField()),
                ("date", models.DateTimeField()),
            ],
            options={
                "db_table": "activity",
            },
        ),
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("team", models.CharField(max_length=100)),
                ("points", models.IntegerField()),
            ],
            options={
                "db_table": "leaderboard",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("members", djongo.models.fields.JSONField(default=list)),
            ],
            options={
                "db_table": "teams",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "workouts",
            },
        ),
    ]
